### ISSUE TITLE
Example doesn't work on iPhone 6

### ISSUE THREAD

**Issue by gerchicov-bp** [ceekay1991/ArchiveUnArchiveIniOS_zip_rar#1]
ld: warning: object file (/Users/gerchicov/Documents/xCode_projects/iOS_ZIP_RAR_compressionAndDecompression/ArchiveUnArchiveIniOS/ThirdParty/UnrarKit/libUnrarKit.a(rar.o)) was built for newer iOS version (7.1) than being linked (7.0)
ld: '/Users/gerchicov/Documents/xCode_projects/iOS_ZIP_RAR_compressionAndDecompression/ArchiveUnArchiveIniOS/ThirdParty/UnrarKit/libUnrarKit.a(rar.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by ceekay1991** [comment]
fixed
